spring.application.name=HikeMate
server.port = ${PORT:8080}

#JPA Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hikemate_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

#Konfigurasi database in memory H2
#spring.datasource.url=jdbc:h2:mem:hikemate_db
#spring.datasource.driver-class-name=org.h2.driver

spring.jackson.time-zone=Asia/Jakarta

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

#File Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.hikemate.upload.path=${UPLOAD_PATH:src/main/resources/static/assets/images/}

#spring.web.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${app.hikemate.upload.path}

#JWT Configuration
app.hikemate.jwt.jwt-secret=hikemate123
app.hikemate.jwt.app-name=hikemate
app.hikemate.jwt.expired=3600

#THIRD API CONFIGURATION: Midtrans
payment.secret.key=${MIDTRANS_API_KEY:U0ItTWlkLXNlcnZlci05Xy1oOElZUkp4ay1fZG05MDlzZ09IbHk6}
payment.url=${MIDTRANS_BASE_URL:https://app.sandbox.midtrans.com/snap/v1/transactions}
payment.fetch.url=${MIDTRANS_FETCH_URL:https://api.sandbox.midtrans.com/v2/}

app.cloudinary-url=${CLOUDINARY_URL:cloudinary://957253723431478:CIHMfAYYT4cOiU7s1hc8azVC82k@dxcnouiqy}
